environments:
  prod:
    adapter: menlo
    api_url: https://api.menlosecurity.com
    vault_path: menlo.prod

  test:
    adapter: menlo
    api_url: https://api.menlosecurity.com
    vault_path: menlo.test
