environments:
  prod:
    adapter: menlo
    api_url: https://api.menlosecurity.com
    token_env: MENLO_API_TOKEN

  test:
    adapter: menlo
    api_url: https://api.menlosecurity.com
    token_env: MENLO_API_TOKEN_TEST
